### ISSUE TITLE
What is all the extra stuff in win-crowdstrike-fix-bootloop-v2.ps1 script?

### ISSUE THREAD

**Issue by mcdonamw** [Azure/repair-script-library#80]
I'm just curious as to what prompted the second version of the Crowdstrike bootloop fix script; win-crowdstrike-fix-bootloop-v2.ps1.  It has a lot of extra stuff I've heard no mention about.  What is all that cleanup for?

**Comment by zmyzheng** [comment]
Hi @mcdonamw , thank you for your interest on the win-crowdstrike-fix-bootloop-v2.ps1 script. The v1 script only delete the corrupt CrowdStrike files on the VM. However, we found this will not always fix the issue on the customer VMs because the registry hive loading can hang forever. On the v2 script, we made 2 enhancements:
1. Besides deleting the corrupt CrowdStrike files, we also load and unload the registry hive config files to the rescue VM. This  is targeted to prevent the registry hang issue.
2. If the registry loading failed because of registry hive DB corrupt, the v2 script then use the ChkReg tool to fix the corrupt registry config files.

Currently,  enhancement 1 has been added to the v1 script as well.  We are working with the support engineer to validate enhancement 2 with customer VMs. Once the validation is done, we will add enhancement 2 to v1 and as well.
